apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: changeme_root_password
  MYSQL_DATABASE: ecommerce_db
  MYSQL_USER: ecommerce_user
  MYSQL_PASSWORD: changeme_password
